---
# This is the labbuilder entry point
# You need to have visited all the component directories and set up the variables 
# in order for this play to run successfully. 
# Please see the README.md file in this directory
- name: "Phase 1 - Generate and deploy builder images"
  ansible.builtin.import_playbook: ./buildimage/main.yml
      
- name: "Phase 2 - bootstrap idm"
  ansible.builtin.import_playbook: ./idm/main.yml

- name: "Phase 3 - bootstrap satellite"
  ansible.builtin.import_playbook: ./sat/main.yml

#- name: "Phase 4 - bootstrap ansible controller"
#  ansible.builtin.import_playbook: ./aap/main.yml
# start time 14:46:00