---
# This is a test play to sync a product 

- name: "Test Product Sync"
  hosts: localhost
  remote_user: root
  gather_facts: yes

  vars_prompt:
  - name: foreman_admin_username
    prompt: "Enter the Username"
    private: "no"
  - name: foreman_admin_password
    prompt: "Enter the password for {{ foreman_admin_username }}"
    private: "yes"

  vars:
    foreman_initial_organization: "RedHatCanada"
    foreman_server_url: "https://sat6.parmstrong.ca"
    foreman_validate_certs: true
    foreman_admin_username: ""
    foreman_admin_password: ""
    product_name: "Red Hat Enterprise Linux Server"

  tasks:

  - name: "Sync the product"
    include_tasks: ./tests/sync_product.yml


