---
# This play will configure the mandatory Content Views for the lab.
# Create requires the ccv loop variable.
- name: Creating the specified content views
  include_tasks: create_ccv.yml
  loop: "{{ ccvs_optional }}"
  loop_control:
    loop_var: ccv
  when: "ccvs_optional is defined"

# Publish requires the cv loop variable. 
- name: Publish the specified content views
  include_tasks: publish_cv_version.yml
  loop: "{{ ccvs_optional }}"
  loop_control:
    loop_var: cv
