---
# This play creates an individual lifecycle environment.

- name: "Create the lifecycle environment"
  katello_lifecycle_environment:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_server_url }}"
    organization: "{{ foreman_initial_organization }}"
    validate_certs: "{{ foreman_validate_certs }}"
    name: "{{ lce.name }}"
    label: "{{ lce.label }}"
    description: "{{ lce.desc }}"
    prior: "{{ lce.prior }}"
    state: present

