---
# This play creates an individual content view from specified paramters
# Call this with a dictionary defining the content-view.
#
# Specify the list as cvs_mandatory or cvs_optional in the vars file
#
# We ARE NOT using auto-publish for composites as we will control that 
# through the monthly content configuration with Tower
#
# Creating the content view is many layered: 
# - create the view
# - add the repositories
# - add the filters
# - add any ansible content
#
# This is one reason why I decided on looping in task calls defined in other files...
 
- name: "Create the content view"
  katello_content_view:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_server_url }}"
    organization: "{{ foreman_initial_organization }}"
    validate_certs: "{{ foreman_validate_certs }}"
    name: "{{ cv.name }}"
    description: "{{ cv.desc }}"
    repositories: "{{ cv.repositories }}"


# Add the filters
- name: "Add the filters to the Content View"
  include_tasks: create_cv_filter.yml
  loop: "{{ cv.filters }}"
  loop_control:
    loop_var: cvf

