---
# Tell Satellite to import the roles
- name: "Call the Satellite ansible import API"
  ansible.builtin.uri:
    url: "{{ satellite_url }}/ansible/api/ansible_roles/sync"
    method: "PUT"
    user: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    force_basic_auth: true
    body: 
      proxy_id: "{{ satellite_api_proxy_id_string }}"
      role_names: "{{ ansible_roles_import_list }}"
    body_format: "body_format: form-urlencoded"
    status_code: 201
