---
# This is the entry point for the foreman_post role tasks
# As this is a role for the configuration of a complex single system, this is a necessarily long and involved file.
# Please take the time to read the documentation especially around the variables that you should set (and those you might wish to leave alone!)
# Content Configuration
# - configure hammer
# - download and install a Red Hat manifest to access content.
# - configure Red Hat repositories.
# - configure content credentials
# - configure any custom products e.g. MSSQL Server
# - synchronize the content
# - create the life cycle environments
# - create the content views
# - create the composite content views
# - create the sync plans
# - attach the sync plans to content
# - configure Activation Keys
# Provisioning Configuration
# - configure OS media
# - configure partition tables templates
# - configure job templates
# - configure provisioning templates
# - configure template synchronization
# - configure OSs
# - download ansible roles for SCAP
# - configure OSCAP content
# - configure OSCAP tailoring files
# - configure OSCAP policy
# - configure Network Domains
# - configure Kerberos REALMs
# - configure Subnets
# - configure PXE provisioning defaults for baremetal discovery
# - configure discovery rules
# - configure schedules
# - configure global parameters
# - configure anything else
# - configure hostgroups
# - add admin users - cloud connector, ansible


- import_tasks: "{{ role_path }}/tasks/configure_hammer.yml"
  tags:
    - basic_config
    - configure_hammer

- import_tasks: "{{ role_path }}/tasks/create_manifest.yml"
  tags:
    - basic_config
    - manifest

- import_tasks: "{{ role_path }}/tasks/fetch_manifest.yml"
  tags:
    - basic_config
    - manifest

- import_tasks: "{{ role_path }}/tasks/upload_manifest.yml"
  tags:
    - basic_config
    - manifest

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_repositories.yml"
  tags:
    - content_config
    - repositories

- import_tasks: "{{ role_path }}/tasks/configure_optional_repositories.yml"
  tags:
    - content_config
    - repositories

- import_tasks: "{{ role_path }}/tasks/configure_custom_products.yml"
  tags:
    - content_config
    - repositories

- import_tasks: "{{ role_path }}/tasks/start_synchronization.yml"
  tags:
    - content_config
    - synch

- import_tasks: "{{ role_path }}/tasks/configure_lifecycle_environments.yml"
  tags:
    - content_config
    - lifecycle

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_cvs.yml"
  tags:
    - content_config
    - content_views

- import_tasks: "{{ role_path }}/tasks/configure_optional_cvs.yml"
  tags:
    - content_config
    - content_views

- import_tasks: "{{ role_path }}/tasks/configure_optional_ccvs.yml"
  tags:
    - content_config
    - content_views

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_sync_plans.yml"
  tags:
    - content_config
    - content_views

- import_tasks: "{{ role_path }}/tasks/configure_optional_sync_plans.yml"
  tags:
    - content_config
    - synch_plans

- import_tasks: "{{ role_path }}/tasks/attach_sync_plans.yml"
  tags:
    - content_config
    - synch_plans

# Configure the Provisioning Components

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_media.yml"
  tags:
    - provisioning_config
    - media

- import_tasks: "{{ role_path }}/tasks/configure_optional_media.yml"
  when: "setup_optional_media == true"
  tags:
    - provisioning_config
    - media

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_ptables.yml"
  tags:
    - provisioning_config
    - ptables

- import_tasks: "{{ role_path }}/tasks/configure_optional_ptables.yml"
  tags:
    - provisioning_config
    - ptables

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_prov_templates.yml"
  tags:
    - provisioning_config
    - prov_templates

- import_tasks: "{{ role_path }}/tasks/configure_optional_prov_templates.yml"
  tags:
    - provisioning_config
    - prov_templates

# Ready for OS creation
# NOTE: RHEL OS is "special" - it is created by Satellite, you must include the version specific kickstart
# as a synchronized repository to get the deployment to work with base components
# Personally, I am of the opinion that this should happen in the background or don't include the OS..
# Work completely when you sync 7Server only. No half measures. #OffSoapBox
#
- import_tasks: "{{ role_path }}/tasks/configure_special_oss.yml"
  tags:
    - provisioning_config
    - os

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_oss.yml"
  tags:
    - provisioning_config
    - os

- import_tasks: "{{ role_path }}/tasks/configure_optional_oss.yml"
  tags:
    - provisioning_config
    - os

# * ActivationKeys
# Again, mandatory (to meet base config), optional (to add to the config - also failing will not stop build till the end of the phase)
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_aks.yml"
  tags:
    - provisioning_config
    - ak

- import_tasks: "{{ role_path }}/tasks/configure_optional_aks.yml"
  tags:
    - provisioning_config
    - ak

# * Domains
# Ditto
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_domains.yml"
  tags:
    - provisioning_config
    - network
    - domains

- import_tasks: "{{ role_path }}/tasks/configure_optional_domains.yml"
  tags:
    - provisioning_config
    - network
    - domains

# * Realms
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_realms.yml"
  tags:
    - provisioning_config
    - network
    - realms

- import_tasks: "{{ role_path }}/tasks/configure_optional_realms.yml"
  tags:
    - provisioning_config
    - network
    - realms

# * Subnets
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_subnets.yml"
  tags:
    - provisioning_config
    - network
    - subnets

- import_tasks: "{{ role_path }}/tasks/configure_optional_subnets.yml"
  tags:
    - provisioning_config
    - network
    - subnets

- import_tasks: "{{ role_path }}/tasks/build_pxe_defaults.yml"
  tags:
    - provisioning_config
    - discovery


- import_tasks: "{{ role_path }}/tasks/configure_mandatory_hostgroups.yml"
  tags:
    - provisioning_config
    - host_groups

- import_tasks: "{{ role_path }}/tasks/configure_optional_hostgroups.yml"
  tags:
    - provisioning_config
    - host_groups

# Note you may define any additional discovery rules here that are required for your
# implementation in Phase 3 Infrastructure
# For others baremetal systems that may part of your platform deployment
# include discovery rules in your Phase 4 configuration
#
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_discovery_rules.yml"
  tags:
    - provisioning_config
    - discovery

- import_tasks: "{{ role_path }}/tasks/configure_optional_discovery_rules.yml"
  tags:
    - provisioning_config
    - discovery

- import_tasks: "{{ role_path }}/tasks/poweron.yml"
  tags:
    - provisioning_config
    - power_on


            
