---
# This is the entry point for the foreman_post role tasks
# As this is a role for the configuration of a complex single system, this is a necessarily long and involved file.
# Please take the time to read the documentation especially around the variables that you should set (and those you might wish to leave alone!)
# Content Configuration
# - configure hammer
# - download and install a Red Hat manifest to access content.
# - configure Red Hat repositories.
# - configure content credentials
# - configure any custom products e.g. MSSQL Server
# - synchronize the content
# - create the life cycle environments
# - create the content views
# - create the composite content views
# - create the sync plans
# - attach the sync plans to content
# - configure Activation Keys
# Provisioning Configuration
# - configure OS media
# - configure partition tables templates
# - configure job templates
# - configure provisioning templates
# - configure template synchronization
# - configure OSs
# - download ansible roles for SCAP
# - configure OSCAP content
# - configure OSCAP tailoring files
# - configure OSCAP policy
# - configure Network Domains
# - configure Kerberos REALMs
# - configure Subnets
# - configure PXE provisioning defaults for baremetal discovery
# - configure discovery rules
# - configure schedules
# - configure global parameters
# - configure anything else
# - configure hostgroups
# - add admin users - cloud connector, ansible


- import_tasks: "{{ role_path }}/tasks/configure_hammer.yml"
  tags:
    - mandatory
    - basic_config
    - configure_hammer

- import_tasks: "{{ role_path }}/tasks/create_manifest.yml"
  tags:
    - mandatory
    - basic_config
    - manifest

- import_tasks: "{{ role_path }}/tasks/fetch_manifest.yml"
  tags:
    - mandatory
    - basic_config
    - manifest

- import_tasks: "{{ role_path }}/tasks/upload_manifest.yml"
  tags:
    - mandatory
    - basic_config
    - manifest

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_repositories.yml"
  tags:
    - mandatory
    - content_config
    - redhat_repos
    - repositories

- import_tasks: "{{ role_path }}/tasks/configure_optional_repositories.yml"
  tags:
    - optional
    - content_config
    - redhat_repos
    - repositories

- import_tasks: "{{ role_path }}/tasks/configure_custom_products.yml"
  tags:
    - mandatory
    - content_config
    - custom_repos
    - repositories

- import_tasks: "{{ role_path }}/tasks/start_synchronization.yml"
  tags:
    - mandatory
    - content_config
    - synch

- import_tasks: "{{ role_path }}/tasks/configure_lifecycle_environments.yml"
  tags:
    - mandatory
    - content_config
    - lifecycle_environments

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_sync_plans.yml"
  tags:
    - mandatory
    - content_config
    - sync_plans

- import_tasks: "{{ role_path }}/tasks/configure_optional_sync_plans.yml"
  tags:
    - optional
    - content_config
    - synch_plans

- import_tasks: "{{ role_path }}/tasks/attach_sync_plans.yml"
  tags:
    - mandatory
    - content_config
    - synch_plans

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_cvs.yml"
  tags:
    - mandatory
    - content_config
    - content_views

- import_tasks: "{{ role_path }}/tasks/configure_optional_cvs.yml"
  tags:
    - optional
    - content_config
    - content_views

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_ccvs.yml"
  tags:
    - mandatory
    - content_config
    - composite_content_views

- import_tasks: "{{ role_path }}/tasks/configure_optional_ccvs.yml"
  tags:
    - optional
    - content_config
    - composite_content_views

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_media.yml"
  tags:
    - mandatory
    - provisioning_config
    - media

- import_tasks: "{{ role_path }}/tasks/configure_optional_media.yml"
  tags:
    - optional
    - provisioning_config
    - media

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_ptables.yml"
  tags:
    - mandatory
    - provisioning_config
    - ptables

- import_tasks: "{{ role_path }}/tasks/configure_optional_ptables.yml"
  tags:
    - optional
    - provisioning_config
    - ptables

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_prov_templates.yml"
  tags:
    - mandatory
    - provisioning_config
    - prov_templates

- import_tasks: "{{ role_path }}/tasks/configure_optional_prov_templates.yml"
  tags:
    - optional
    - provisioning_config
    - prov_templates
    
- import_tasks: "{{ role_path }}/tasks/configure_mandatory_oss.yml"
  tags:
    - mandatory
    - provisioning_config
    - os

- import_tasks: "{{ role_path }}/tasks/configure_optional_oss.yml"
  tags:
    - optional
    - provisioning_config
    - os

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_aks.yml"
  tags:
    - mandatory
    - provisioning_config
    - activation_keys

- import_tasks: "{{ role_path }}/tasks/configure_optional_aks.yml"
  tags:
    - optional
    - provisioning_config
    - activation_keys

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_domains.yml"
  tags:
    - mandatory
    - provisioning_config
    - network
    - domains

- import_tasks: "{{ role_path }}/tasks/configure_optional_domains.yml"
  tags:
    - optional
    - provisioning_config
    - network
    - domains

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_realms.yml"
  tags:
    - mandatory
    - provisioning_config
    - network
    - realms

- import_tasks: "{{ role_path }}/tasks/configure_optional_realms.yml"
  tags:
    - optional
    - provisioning_config
    - network
    - realms

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_subnets.yml"
  tags:
    - mandatory
    - provisioning_config
    - network
    - subnets

- import_tasks: "{{ role_path }}/tasks/configure_optional_subnets.yml"
  tags:
    - optional
    - provisioning_config
    - network
    - subnets

- import_tasks: "{{ role_path }}/tasks/build_pxe_defaults.yml"
  tags:
    - mandatory
    - provisioning_config
    - discovery

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_compute_resources.yml"
  tags:
    - mandatory
    - provisioning_config
    - compute_resources

- import_tasks: "{{ role_path }}/tasks/configure_optional_compute_resources.yml"
  tags:
    - optional
    - provisioning_config
    - compute_resources

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_compute_profiles.yml"
  tags:
    - mandatory
    - provisioning_config
    - compute_profiles

- import_tasks: "{{ role_path }}/tasks/configure_optional_compute_profiles.yml"
  tags:
    - optional
    - provisioning_config
    - compute_profiles

- import_tasks: "{{ role_path }}/tasks/configure_virtwho.yml"
  tags:
    - mandatory
    - provisioning_config
    - virt_who

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_git_repos.yml"
  tags:
    - mandatory
    - provisioning_config
    - clone_git_repos

- import_tasks: "{{ role_path }}/tasks/configure_optional_git_repos.yml"
  tags:
    - optional
    - provisioning_config
    - clone_git_repos

- import_tasks: "{{ role_path }}/tasks/ensure_import_roles.yml"
  tags:
    - mandatory
    - provisioning_config
    - ansible_import_roles

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_scap_content.yml"
  tags:
    - mandatory
    - provisioning_config
    - scap_contents

- import_tasks: "{{ role_path }}/tasks/configure_optional_scap_content.yml"
  tags:
    - optional
    - provisioning_config
    - scap_contents

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_scap_tailoring_files.yml"
  tags:
    - mandatory
    - provisioning_config
    - scap_tailoring_files

- import_tasks: "{{ role_path }}/tasks/configure_optional_scap_tailoring_files.yml"
  tags:
    - optional
    - provisioning_config
    - scap_tailoring_files

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_hostgroups.yml"
  tags:
    - mandatory
    - provisioning_config
    - host_groups

- import_tasks: "{{ role_path }}/tasks/configure_optional_hostgroups.yml"
  tags:
    - optional
    - provisioning_config
    - host_groups

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_scap_policies.yml"
  tags:
    - mandatory
    - provisioning_config
    - scap_policies

- import_tasks: "{{ role_path }}/tasks/configure_optional_scap_policies.yml"
  tags:
    - optional
    - provisioning_config
    - scap_policies

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_discovery_rules.yml"
  tags:
    - mandatory
    - provisioning_config
    - discovery_rules

- import_tasks: "{{ role_path }}/tasks/configure_optional_discovery_rules.yml"
  tags:
    - optional
    - provisioning_config
    - discovery_rules

- import_tasks: "{{ role_path }}/tasks/configure_mandatory_global_parameters.yml"
  tags:
    - mandatory
    - provisioning_config
    - global_parameters

- import_tasks: "{{ role_path }}/tasks/configure_optional_global_parameters.yml"
  tags:
    - optional
    - provisioning_config
    - global_parameters

# End of Satellite Configuration
