---
# Use the redhat.satellite.manifest role

- name: "Upload the manifest"
  ansible.builtin.include_role:
    name: redhat.satellite.manifest
  vars:
    satellite_server_url: "{{ satellite_url }}"
    satellite_username: "{{ satellite_admin_username }}"
    satellite_password: "{{ satellite_admin_password }}"
    satellite_organization: "{{ satellite_initial_organization }}"
    satellite_manifest_path: "{{ manifest_path }}"
