---
- name: "buildimage"
  hosts: build_control
  remote_user: ansiblerunner
  become: false
  gather_facts: false
  connection: local
  vars_files:
    - vars/aws_vars.yml
    - vars/aws_vault.yml
    - vars/builder_vars.yml
    - vars/builder_vault.yml
#    - vars/vmware_vars.yml
#    - vars/vmware_vault.yml
    - vars/idm_vars.yml
#    - vars/idm_vault.yml
#    - vars/sat_vars.yml
#    - vars/sat_vault.yml

  tasks:
    - name: "Get the imagebuilder image"
      ansible.builtin.include_tasks: tasks/buildimage.yml
      tags:
        - buildimage

    - name: "build idm VM"
      ansible.builtin.include_tasks: tasks/create_idm_ec2.yml
      tags:
        - idm


#    - name: "Configure image on vCenter"
#      ansible.builtin.include_tasks: tasks/load_image_vcenter.yml
#      tags:
#        - image_2_vcenter
#
#    - name: "Initialize primary identity management server"
#      ansible.builtin.include_tasks: tasks/initialize_idm_primary.yml
#      tags:
#        - build_idm_primary
#
#    - name: "Initialize satellite server"
#      ansible.builtin.include_tasks: tasks/initialize_sat_primary.yml
#      tags:
#        - build_satellite_primary
