---
- name: initial check setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars_files:
    - vars/aws_vars.yml
    - vars/aws_vault.yml
    - vars/builder_vars.yml
    - vars/builder_vault.yml
#    - vars/vmware_vars.yml
#    - vars/vmware_vault.yml
    - vars/idm_vars.yml
#    - vars/idm_vault.yml
#    - vars/sat_vars.yml
#    - vars/sat_vault.yml
  vars:
    ec2_wait: true
  tasks:
    - name: Get last composer AMI
      ec2_ami_info:
        region: "{{ ec2_region }}"
        owners: 463606842039
        filters:
          name: "composer-api-*"
          architecture: "x86_64"
      register: amis

    - name: Save composer AMI image
      set_fact:
        composer_ami: >
          {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

    - name: Debug
      debug:
        msg: '{{ composer_ami }}'
