---
# IdM Firewall rules.
# This environment requires RHEL7 
# firewalld is installed by default
- name: "Ensure firewalld is installed"
  yum:
    name: "firewalld"
    state: latest

- name: "Ensure firewalld is running"
  service:
    name: "firewalld"
    enabled: true
    state: started

- name: "Ensure https ports are open"
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
    zone: public
  loop:
    - https
    - freeipa-ldap
    - freeipa-ldaps
    - dns
    - ntp
    - kerberos
    - freeipa-replication
    - freeipa-trust

