---
# This task controls the install and initial configuration of IdM
- import_tasks: role_begin.yml

- name: "Enable the RHEL Server repo required for IdM"
  rhsm_repository: 
    name: "rhel-7-server-rpms"
    state: enabled

# to handle bug see: https://access.redhat.com/solutions/3948781
#
- name: "Enable the optional repo temporarily"
  rhsm_repository: 
    name: "rhel-7-server-optional-rpms"
    state: enabled

- name: "Ensure the ansible-freeipa roles are installed"
  yum:
    name: "ansible-freeipa"
    state: latest

- name: "Updating the system... this may take a while."
  yum:
    name: "*"
    state: latest
 
#- name: "Configure the IdM firewall"
#  import_tasks: idm_firewall.yml
- name: Apply the IdM Server role to buildmaster
  include_roles:
  - ipaserver

- include_tasks: add_std_user_groups.yml
- include_tasks: add_std_users.yml
- include_tasks: add_std_sudo_rules.yml
- include_tasks: add_std_hbac_rules.yml
- include_tasks: role_complete.yml

