---
- name: "buildimage"
  hosts: build_control
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - ../vars/builder_vault.yml
    - ../vars/builder_vars.yml
  
  tasks:
    - name: "Get the imagebuilder image"
      ansible.builtin.include_tasks: tasks/buildimage.yml
      tags:
        - buildimage
