---
- name: "Ensure that the RHEL repository is enabled"
  command: "subscription-manager repos --enable=rhel-7-server-rpms"

- name: "Use satellite-maintain to control IdM Client installation"
  command: "satellite-maintain packages install ipa-client"

- name: "Unregister the host if it is already registered"
  command: "ipa-client-install --uninstall --unattended"
  ignore_errors: true

- name: "Setup the IdM Client"
  command: "ipa-client-install --domain={{ ansible_domain }} --server={{ groups['build_master'] | first }} --realm={{ ansible_domain | upper }} --principal=admin --password={{ idm_admin }} --mkhomedir --ssh-trust-dns --enable-dns-updates --unattended"
  when: "ipa_install_client == true"

