---
- name: "Build the satellite primary"
  hosts: sat_primary
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  tasks:

    - name: "Apply role of satellite_pre to {{ ansible_fqdn }}"
      ansible.builtin.include_role:
        name: satellite_pre

    - name: "Apply role of satellite to {{ ansible_fqdn }}"
      ansible.builtin.include_role:
        name: satellite

    - name: "Apply role of satellite_post to {{ ansible_fqdn }}"
      ansible.builtin.include_role:
        name: satellite_post

    - name: "Waiting {{ pause_minutes }} minutes for Discovery"
      ansible.builtin.pause:
        minutes: "{{ pause_minutes }}"
        prompt: "Press Ctrl+C then - press c to continue early OR press a to abort"

