---
- name: "Build the satellite primary"
  hosts: sat_primary
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - vars/satellite_vault.yml
    - vars/satellite_pre_vars.yml
    - vars/satellite_vars.yml

  tasks:

    - name: "Apply role of satellite_pre to {{ ansible_fqdn }}"
      ansible.builtin.include_role:
        name: satellite_pre

    - name: "Apply role of satellite to {{ ansible_fqdn }}"
      ansible.builtin.include_role:
        name: satellite

    - name: "Apply satellite_post role to target"
      ansible.builtin.include_role:
        name: satellite_post

