---
- name: "Test Task"
  hosts: sat_primary
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - vars/satellite_vault.yml
    - vars/satellite_pre_vars.yml
    - vars/satellite_vars.yml

  tasks:
    - import_tasks: "roles/satellite_post/tasks/configure_mandatory_subnets.yml"
    - import_tasks: "roles/satellite_post/tasks/configure_optional_subnets.yml"
    - import_tasks: "roles/satellite_post/tasks/configure_mandatory_compute_resources.yml"
    - import_tasks: "roles/satellite_post/tasks/configure_optional_compute_resources.yml"
    - import_tasks: "roles/satellite_post/tasks/configure_virtwho.yml"


