---
- name: "Test Task"
  hosts: sat_primary
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - vars/satellite_vault.yml
    - vars/satellite_pre_vars.yml
    - vars/satellite_vars.yml

  roles:
    - satellite_post
