---
# AWS specific initialization starts here
- name: "AWS specific initialization"
  hosts: build_control
  remote_user: localhost
  connection: local
  become: false
  vars_files:
    - '~/rhisbuilder_vault.yml'
  tasks:
    - name: "Debug message"
      debug:
        msg: "AWS init starts here"
