---
# AWS specific initialization starts here
- name: "AWS specific network infrastructure reconfiguration to use IDM as DNS server"
  hosts: build_control
  remote_user: localhost
  connection: local
  become: false
  vars_files:
    - '~/rhisbuilder_vault.yml'
  tasks:
    - name: "AWS inventory and DHCP option setting"
      block:
        - name: Build inventory for subsequent tasks
          ansible.builtin.include_role:
            name: roles/build_bootstrap_inventory

        - name: "AWS-specific configuration to configure IDM as DNS Server for VPC"
          amazon.aws.ec2_vpc_dhcp_option:
            vpc_id: '{{ ec2_vpc_id }}'
            region: '{{ ec2_region }}'
            inherit_existing: true
            domain_name: '{{ ipa_server_domain }}'
            dns_servers:
              - "{{ idm_instance['private_ip_address'] }}"

- name: Restart NetworkManager to get nodes to pick up new DHCP options
  hosts: aws_nodes
  become: true
  gather_facts: true
  tasks:
    - name: "Restart NetworkManager on EC2 nodes"
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
