---
- name: initial check setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: workshop collection final check
      block:
        - name: run pre-check role to make sure workshop will complete provisioning
          include_role:
            name: roles/workshop_check_setup

        - name: run AWS check setup if using AWS
          include_role:
            name: roles/aws_check_setup

      rescue:
        - name: Error with setup
          fail:
            msg: The provisioner has failed during initial check_setup, please scroll up to see exact error.  Open an issue on https://github.com/ansible/workshops/issues

#    - name: add dns entries
#      include_role:
#        name: roles/aws_dns
#      when:
#        - dns_type is defined
#        - dns_type == "aws"

    - name: Provision network stuff
      include_role:
        name: roles/manage_ec2_infra
