---
# ensure that the foreman-proxy realm user can update forward and reverse records in the domain

# append the foreman_proxy_BIND_update_policy to forward lookup zones
# append the foreman_proxy_BIND_update_policy to reverse lookup zones