---
# This task copies the manifest from the ansible control host
# and uploads it to the satellite to enable content
#
# manifest_path is the location on the control host to which the role will have downloaded the manifest 

- name: "Remove any existing manifest"
  katello_manifest:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_server_url }}"
    organization: "{{ foreman_initial_organization }}"
    validate_certs: "{{ foreman_validate_certs }}"
    manifest_path: "{{ manifest_path }}"
    state: absent

- name: "Upload the specified manifest"
  katello_manifest:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_server_url }}"
    organization: "{{ foreman_initial_organization }}"
    validate_certs: "{{ foreman_validate_certs }}"
    manifest_path: "{{ manifest_path }}"
    state: present

- name: "Tell Satellite to refresh the manifest with the CDN"
  katello_manifest:
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_server_url }}"
    organization: "{{ foreman_initial_organization }}"
    validate_certs: "{{ foreman_validate_certs }}"
    manifest_path: "{{ manifest_path }}"
    state: refreshed

